vault:
  path: "yout obsidian vault path"

backup:
  path: "your backup dir"

template:
  path: "your template dir"

plugins:
  rest-api:
    url: "http://your obsidian vault url"
    token: "your obsidian vault token"
